global AA BB CC DD EE FF GG HH II JJ KK LL MM NN OO PP QQ RR SS TT KKK NNN; 
GPC_B = 153.4; 
rPGU = 35;  rBGU = 70;  rGGU = 20;  rHGP = 155;  rHGU = 20; 
QGP = 15.1;  QGA = 2.5;  QGB = 5.9;  QGG = 10.1;  QGL = 12.6; 
VBT = 4.5;  VPT = 63; 
TGP = 5;  TB = 2.1; 
GHC_B = GPC_B+rPGU/QGP; 
GKC_B = GHC_B; 
GBC_B = GHC_B-rBGU/QGB; 
GSC_B = GHC_B-rGGU/QGG; 
GLC_B = (QGA*GHC_B+QGG*GSC_B+rHGP-rHGU)/QGL; 
GBT_B = GBC_B-rBGU*TB/VBT; 
GPT_B = GPC_B-rBGU*TGP/VPT; 
IPC_B = 5.9; 
FPIC = 0.15;  FKIC = 0.3;  FLIC = 0.4; 
QIP = 1.05;  QIH = 3.12;  QIB = 0.45;  QIK = 0.72;  QIL = 0.9;  QIG = 0.72;  QIA = 0.18; 
TIP = 20; 
VPT = 6.3; 
GAMA = KKK;
K = NNN;
Q0 = 6.33; 
M1 = QQ; 
IHC_B = IPC_B/(1-FPIC); 
IKC_B = IHC_B*(1-FKIC); 
IBC_B = IHC_B; 
ISC_B = IHC_B; 
IPT_B = IPC_B-(QIP*TIP*(IHC_B-IPC_B)/VPT); 
ILC_B = (QIH*IHC_B-QIB*IHC_B-QIK*IKC_B-QIP*IPC_B)/QIL; 
rPIR_B = QIL*ILC_B/(1-FLIC)-QIG*ISC_B-QIA*IHC_B; 
X_B = GHC_B^3.27/(8.595611e6+5.93*GHC_B^3.02); 
P_Inf_B = X_B^1.11; 
Y_B = P_Inf_B; 
P_B = P_Inf_B; 
I_B = X_B; 
Q_B = (K*Q0+GAMA*P_Inf_B)/(K+M1*Y_B); 
S_B = M1*Y_B*Q_B; 
% save Basal_Condition GBC_B GBT_B GHC_B GSC_B GLC_B GKC_B GPC_B GPT_B IBC_B IHC_B ISC_B ILC_B IKC_B IPC_B IPT_B rPIR_B X_B S_B P_Inf_B Y_B Q_B 
X = [GBC_B GBT_B GHC_B GSC_B GLC_B GKC_B GPC_B GPT_B 1 0 1 IBC_B IHC_B ISC_B ILC_B IKC_B IPC_B IPT_B 1]'; 
P = P_B; 
I = I_B; 
Q = Q_B; 
% save SS_Con X P I Q 